version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: carrental_sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin123!!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "Strong_Passw0rd!",
          "-Q",
          "SELECT 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  web:
    image: car_rental
    container_name: carrental_web
    ports:
      - "8080:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;
        Database=CarRentalDB;
        User Id=sa;
        Password=Admin123!;
        TrustServerCertificate=True;
        Encrypt=False

volumes:
  sql_data:
